export const SPLASH_TEXTS = [
  "Also try Minecraft!",
  "Kid named finger:",
  "Penny's Big Breakway has a really good soundtrack",
  "spongr",
  "-160 -304 (nether) Hoglin Farm",
  "Do you even know?",
  "Who are the cookies and why are they running",
  "Oh so that's why the mobile port was taking so long",
  "This update is significant",
  "Me, the king of unfinished projects",
  "save me phighting ost",
  "it’s time to drink water",
  "Sorry...echolotl...",
  "Homer ⚠️⚠️⚠️",
  "I am game of the year",
  "My brain is getting cow milked",
  "It's called AP for a reason",
  "Why do they call it oven when you of in the cold food of out hot eat the food?",
  "[Vue Router warn]",
  "Bacon, Egg, and Cheese McEggle with the tomato sauce on it",
  "You gotta power edge before you lightning goon",
  "I'm putting a bunny in my house so I need a boat on the ghast",
  "Hey, could you guys come up with some insults for me to use when we cook yall? thx!",
  "hopes and dreams + C",
  "Can you be a little quieter while being chopped",
  "green and purple forever",
  "first meth challenge"
];
