// generated by claude
/**
 * Palette Image Generator
 *
 * This script automatically generates color palette images for all characters
 * that have a color_palette defined in their frontmatter.
 *
 * Generated images are saved to: public/images/palettes/[character-slug].png
 *
 * Usage:
 *   - Run manually: bun run palettes:generate
 *   - Runs automatically at build time via Nuxt hooks
 *
 * Each palette image is a horizontal strip of color swatches, with each swatch
 * being 100x100 pixels. The total width depends on the number of colors.
 */

import { existsSync, mkdirSync, readdirSync, readFileSync } from "fs";
import { join } from "path";
import sharp from "sharp";
import * as yaml from "js-yaml";

const CONTENT_CHARACTERS_DIR = "content/characters";
const PUBLIC_PALETTES_DIR = "public/images/palettes";
const SWATCH_WIDTH = 100;
const SWATCH_HEIGHT = 100;

interface CharacterData {
  slug: string;
  name: string;
  color_palette?: string[];
  [key: string]: any;
}

async function createPaletteImage(
  colors: string[],
  outputPath: string,
  characterName: string,
): Promise<void> {
  try {
    const totalWidth = colors.length * SWATCH_WIDTH;
    const height = SWATCH_HEIGHT;

    // Create SVG with color swatches
    const swatches = colors
      .map((color, index) => {
        const x = index * SWATCH_WIDTH;
        return `<rect x="${x}" y="0" width="${SWATCH_WIDTH}" height="${height}" fill="${color}"/>`;
      })
      .join("\n");

    const svg = `
      <svg width="${totalWidth}" height="${height}" xmlns="http://www.w3.org/2000/svg">
        ${swatches}
      </svg>
    `;

    // Convert SVG to PNG using sharp
    await sharp(Buffer.from(svg)).png().toFile(outputPath);

    console.log(`✓ Created palette for ${characterName}: ${outputPath}`);
  } catch (error) {
    console.error(`✗ Failed to create palette for ${characterName}:`, error);
    throw error;
  }
}

async function generatePalettes(): Promise<void> {
  console.log("🎨 Generating color palette images...\n");

  // Ensure the palettes directory exists
  if (!existsSync(PUBLIC_PALETTES_DIR)) {
    mkdirSync(PUBLIC_PALETTES_DIR, { recursive: true });
    console.log(`📁 Created directory: ${PUBLIC_PALETTES_DIR}\n`);
  }

  let processed = 0;
  let skipped = 0;
  let errors = 0;

  // Read all character files
  const characterFiles = readdirSync(CONTENT_CHARACTERS_DIR).filter((file) =>
    file.endsWith(".md"),
  );

  for (const file of characterFiles) {
    try {
      const filePath = join(CONTENT_CHARACTERS_DIR, file);
      const fileContent = readFileSync(filePath, "utf8");

      // Extract frontmatter
      const frontmatterMatch = fileContent.match(/^---\r?\n([\s\S]*?)\r?\n---/);
      if (!frontmatterMatch) {
        console.log(`⏭ Skipping ${file}: No frontmatter found`);
        skipped++;
        continue;
      }

      const data = yaml.load(frontmatterMatch[1]) as CharacterData;

      if (!data.slug) {
        console.log(`⏭ Skipping ${file}: No slug found`);
        skipped++;
        continue;
      }

      if (!data.color_palette || data.color_palette.length === 0) {
        console.log(
          `⏭ Skipping ${data.name || data.slug}: No color palette found`,
        );
        skipped++;
        continue;
      }

      // Generate palette image
      const outputPath = join(PUBLIC_PALETTES_DIR, `${data.slug}.png`);
      await createPaletteImage(
        data.color_palette,
        outputPath,
        data.name || data.slug,
      );
      processed++;
    } catch (error) {
      errors++;
      console.error(`Error processing ${file}:`, error);
    }
  }

  console.log(`\n📊 Summary:`);
  console.log(`✓ Processed: ${processed}`);
  console.log(`⏭ Skipped: ${skipped}`);
  console.log(`✗ Errors: ${errors}`);

  if (errors === 0) {
    console.log("\n🎉 All palette images generated successfully!");
  } else {
    console.log(`\n⚠️ Completed with ${errors} errors.`);
  }
}

async function main() {
  try {
    await generatePalettes();
  } catch (error) {
    console.error("Fatal error:", error);
    process.exit(1);
  }
}

// Run if this file is executed directly
main();
